# vim:ft=toml

{{ if .tags.devToolsCli.enabled }}
{{ $mermaidAsciiVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/AlexanderGrooff/mermaid-ascii/releases/latest" | trim | base }}
[".local/bin/mermaid-ascii"]
	type = "file"
	refreshPeriod = "168h"
	executable = true
	url = "https://github.com/AlexanderGrooff/mermaid-ascii/releases/download/{{ $mermaidAsciiVersion }}/mermaid-ascii_{{ .chezmoi.os | title }}_{{ if eq .chezmoi.arch "amd64" }}x86_64{{ else if eq .chezmoi.arch "arm64" }}arm64{{ end }}.tar.gz"
[".local/bin/mermaid-ascii".filter]
		command = "tar"
		args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mermaid-ascii"]

# An extremely fast directory and filename linter
{{ $lslintVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/loeffel-io/ls-lint/releases/latest" | trim | base | trimPrefix "v" }}
[".local/bin/ls-lint"]
	type = "file"
	refreshPeriod = "168h"
	executable = true
	url = "https://github.com/loeffel-io/ls-lint/releases/download/v{{ $lslintVersion }}/ls-lint-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
{{ end }}

{{ if .tags.hashiCli.enabled }}
{{ $terraformDocsVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/terraform-docs/terraform-docs/releases/latest" | trim | base | trimPrefix "v" }}
[".local/bin/terraform-docs"]
	type = "archive-file"
	refreshPeriod = "168h"
	executable = true
	path = "terraform-docs"
	url =  "https://github.com/terraform-docs/terraform-docs/releases/download/v{{ $terraformDocsVersion }}/terraform-docs-v{{ $terraformDocsVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
{{ end }}

{{ if .tags.limaCli.enabled }}
{{ $limaVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/lima-vm/lima/releases/latest" | trim | base | trimPrefix "v" }}

{{ $limaGuestAgent := "aarch64" }}
{{ if eq .chezmoi.arch "amd64" }}
	{{ $limaGuestAgent = "x86_64" }}
{{ else if eq .chezmoi.arch "arm64" }}
	{{ $limaGuestAgent = "aarch64" }}
{{ end }}

{{ range list "bin/lima" "bin/limactl" (print "share/lima/lima-guestagent." "Linux-" ($limaGuestAgent) ".gz") }}
[".local/{{ . }}"]
	type = "archive-file"
	refreshPeriod = "168h"
	stripComponents = 1
	path = "{{ . }}"
	url = "https://github.com/lima-vm/lima/releases/download/v{{ $limaVersion }}/lima-{{ $limaVersion }}-{{ $.chezmoi.os | title }}-{{ if eq $.chezmoi.arch "amd64" }}x86_64{{ else if eq $.chezmoi.os "darwin" }}arm64{{ else if eq $.chezmoi.os "linux" }}arm64{{ end }}.tar.gz"
{{ end }}

[".local/share/lima"]
	type = "archive"
	refreshPeriod = "168h"
	stripComponents = 3
	url = "https://github.com/lima-vm/lima/releases/download/v{{ $limaVersion }}/lima-additional-guestagents-{{ $limaVersion }}-{{ $.chezmoi.os | title }}-{{ if eq $.chezmoi.arch "amd64" }}x86_64{{ else if eq $.chezmoi.os "darwin" }}arm64{{ else if eq $.chezmoi.os "linux" }}arm64{{ end }}.tar.gz"
{{ end }}
