add_newline = false
format = """$directory$character"""
right_format = """$all"""

[directory]
style = 'bold blue'
# truncation_length = 2
# truncation_symbol = '…/'
# disabled = true

[directory.substitutions]
'Applications' = ' '
'Desktop' = ' '
'Development' = ' '
'Documents' = '󰈙 '
'Downloads' = ' '
'Library' = ' '
'Movies' = '󰟞 '
'Music' = ' '
'Pictures' = ' '
'Public' = '󱔔 '
'Sites' = '󰖟 '
'Sync' = '󰓦 '
'Virtual Machines.localized' = ' '
'Virtual Machines' = ' '
'VirtualBox' = ' '
'.config' = ' '

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'blue'
symbol = "  "

[golang]
format = '[ $version](bold cyan) '

[kubernetes]
symbol = '☸'
disabled = false
detect_files = ['k8s', 'Dockerfile']
detect_extensions = ['yaml']
format = '[$symbol$context( \($namespace\))]($style) '
[kubernetes.context_aliases]

[swift]
disabled = true
