#!/usr/bin/env bash

# Mail #########################################################################
# Disable send and reply animations in Mail.app
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true

# Copy email addresses as `Foo Bar <foo@example.com>` instead of `foo@example.com` in Mail.app
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool true

# Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app
defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"

# Display emails in threaded mode, sorted by date (oldest at the top)
defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "no"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "YES"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "last-saved-date"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SearchSortDescending" -string "YES"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SearchSortOrder" -string "rank"

# Enable inline attachments
defaults write com.apple.mail DisableInlineAttachmentViewing -bool false

# Enable automatic spell checking
defaults write com.apple.mail SpellCheckingBehavior -string "InlineSpellCheckingEnabled"
