#!/usr/bin/env bash

opts=$@

case "$opts" in
	toggle)
		wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; notify-send --urgency=low --icon=audio-on "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
		;;
	up)
		wpctl set-volume --limit 1.5 @DEFAULT_AUDIO_SINK@ 5%+; notify-send --urgency=low --icon=audio-volume-high "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
		;;
	down)
		wpctl set-volume --limit 1.5 @DEFAULT_AUDIO_SINK@ 5%-; notify-send --urgency=low --icon=audio-volume-high "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
		;;
	micmute)
		wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle; notify-send --urgency=low --icon=mic-on "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"
		;;
	*)
		notify-send --urgency=low --icon=audio-volume "$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
		;;
esac
