[global]

[ids]
*

[main]
# capslock = layer(capslock)
capslock = layer(control)

leftcontrol = layer(control)
rightcontrol = layer(control)

leftshift = layer(shift)
rightshift = layer(shift)

leftmeta = layer(cmd)
rightmeta = layer(cmd)

leftalt = layer(alt)
rightalt = layer(alt)

include common
