[ids]
0b05:19b6

[main]
f23+leftshift+leftmeta = layer(alt)

capslock = layer(control)

leftcontrol = layer(control)
rightcontrol = layer(control)

leftshift = layer(shift)
rightshift = layer(shift)

leftmeta = layer(alt)
rightmeta = layer(alt)

leftalt = layer(cmd)
rightalt = layer(cmd)

include common
