#!/usr/bin/env bash

# Accept an arg '+' or '-'
direction=$1

# Get monitor info
monitor_data=$(hyprctl monitors -j)
focused_name=$(echo $monitor_data | jq -r '.[] | select(.focused == true) | .name')




if [ "$focused_name" == "eDP-1" ]; then
	# Internal display is focused -> use brillo
	if [ "$direction" == "-" ]; then
		brillo -u 150000 -U 8
	else
		brillo -u 150000 -A 8
	fi
else
	# External display is focused -> use ddcutil
	# But *which* external display?
	focused_id=$(echo $monitor_data | jq -r '.[] | select(.focused == true) | .id')
	ddcutil --display=$focused_id setvcp 10 $direction 8
fi







iDIR="$HOME/.config/mako/icons"


# Get icons
get_icon() {
	current="$(get_backlight)"
	if [[ ("$current" -ge "0") && ("$current" -le "19200") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "19200") && ("$current" -le "38400") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "38400") && ("$current" -le "57600") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "57600") && ("$current" -le "76800") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "76800") && ("$current" -le "96000") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	if [ "$focused_name" == "eDP-1" ]; then
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(internal_get_backlight)"
	else
		# TODO: add external
	fi
}

# Get brightness
internal_get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl g))
	echo "${LIGHT}"
}

# Increase brightness
internal_inc_backlight() {
	brightnessctl s +5% && get_icon && notify_user
}

# Decrease brightness
internal_dec_backlight() {
	brightnessctl s 5%- && get_icon && notify_user
}

	# External display is focused -> use ddcutil
external_inc_backlight() {
	# Get external display
	focused_id=$(echo $monitor_data | jq -r '.[] | select(.focused == true) | .id')
	ddcutil --display=$focused_id setvcp 10 $direction 8
}


# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
