source 'https://rubygems.org'

group :development do
  gem 'berkshelf'
  gem 'chefspec'
  gem 'serverspec'

  gem 'test-kitchen'
  gem 'kitchen-vagrant'

  gem 'rubycritic'
  gem 'foodcritic'
  gem 'rubocop'
  gem 'tailor'
  gem 'rspec'
  gem 'rspec-command'

  gem 'minitest'
  gem 'minitest-chef-handler'

  gem 'rake'

  gem 'guard'
  gem 'guard-rubycritic'
  gem 'guard-foodcritic'
  gem 'guard-rubocop'
  gem 'guard-kitchen'
  gem 'guard-sheller'
  gem 'guard-rspec'
  gem 'guard-minitest'
  gem 'guard-bundler'
  gem 'terminal-notifier-guard'

  gem 'hubrelease'

  gem 'stove'
  gem 'emeril'
end

group :travis do
  gem 'travis'
end


# group :package do
#   gem 'bento'
#   gem 'fpm'
# end

# group :vagrant do
#   gem 'vagrant', github: 'mitchellh/vagrant'
#   gem 'vagrant-berkshelf', github: 'berkshelf/vagrant-berkshelf'
#   gem 'vagrant-omnibus', github: 'schisamo/vagrant-omnibus'
#   gem 'vagrant-box-updater', github: 'spil-ruslan/vagrant-box-updater'
#   gem 'vagrant-vmware-fusion'
# end
