[nvim]
	dependencies = [
		"rust",
		"go",
		"npm",
		"ruby",
		"python"
	]
	alpine = [
		"neovim",
	]
	darwin = [
		"neovim"
	]
	fedora = [
		"neovim"
	]
	cargo = [
		"stylua"
	]
	go = [
		"github.com/sachaos/viddy@latest",
		"github.com/danielgatis/imgcat@latest",
		"github.com/go-delve/delve/cmd/dlv@latest",
		"github.com/charmbracelet/glow@latest",
		"github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2",
		"github.com/mgechev/revive@latest"
	]
	pip3 = [
		"neovim",
		"flake8",
		"yamllint",
		"gitlint",
		"ruff"
	]
	gem = [
		"neovim",
		"rubocop"
	]
	npm = [
		"neovim",
		"cspell",
		"@commitlint/cli",
		"@commitlint/config-conventional"
	]
